#!/bin/zsh
std=../../gpsbabel/gpsbabel
spl=./gpsbabel.amd64
csv=${1:-../San_Francisco.csv}
name=${csv%.csv}
$spl -i unicsv -f "${csv}" -x sort,shortnum -o nauteek -F "${name}.nk"
$std -i unicsv -f "${csv}" -o gpx -F "${name}.gpx"
xmlstarlet ed -L -u '/_:gpx/_:time' -v $(date -r "${csv}" -u '+%FT%T.%3NZ') "${name}.gpx"
$std -i unicsv -f "${csv}" -o html -F "${name}.html"
( cd ../San_Francisco.shp; ogr2ogr -overwrite -f "ESRI Shapefile" . convert-to-shp.vrt )
for df in noaa dmm dms ; do
  ./conv.py $df < "${csv}" > "${name}.${df}"
done
